// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main__container': string;
  'main__container_content': string;
  'main__container_content_info': string;
  'main__container_content_items': string;
  'main__container_content_submit': string;
  'main__container_price': string;
}
export const cssExports: CssExports;
export default cssExports;
