// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer__main': string;
  'footer__main_content': string;
  'footer__main_content_links': string;
  'footer__main_content_logo': string;
}
export const cssExports: CssExports;
export default cssExports;
