// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item__container': string;
  'item__container_info': string;
  'item__container_item': string;
  'item__container_item_actions': string;
  'item__container_item_actions_addToBasket': string;
  'item__container_item_actions_addToFavorite': string;
  'item__container_item_actions_buynow': string;
  'item__container_item_available': string;
  'item__container_item_description': string;
  'item__container_item_price': string;
  'item__container_item_title': string;
  'item__container_preview': string;
  'toastBody': string;
  'toastContainer': string;
  'toastProgress': string;
}
export const cssExports: CssExports;
export default cssExports;
