// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'login__main': string;
  'login__main_container': string;
  'login__main_container_error': string;
  'login__main_container_form': string;
  'login__main_container_form_checkbox': string;
  'login__main_container_newAcc': string;
  'login__main_container_title': string;
  'login__main_form': string;
  'login__main_login_button': string;
  'login__main_logo': string;
}
export const cssExports: CssExports;
export default cssExports;
