// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main__container': string;
  'main__container_categories': string;
  'main__container_categories_search': string;
  'main__container_categories_settings': string;
  'main__container_products': string;
  'main__container_setting': string;
  'main__container_settings_container': string;
  'search': string;
  'main__container_products_not_found': string;
  'main__container_products_not_found_container': string;
  'main__container_products_not_found_title': string;
  'main__container_products_not_found_description': string;
}
export const cssExports: CssExports;
export default cssExports;
