// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navbar': string;
  'navbar__content': string;
  'navbar__dropping_menu': string;
  'navbar__useravatar': string;
}
export const cssExports: CssExports;
export default cssExports;
