// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'notfound__main': string;
  'notfound__main_container': string;
  'notfound__main_container_title': string;
}
export const cssExports: CssExports;
export default cssExports;
