// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'product__container': string;
  'product__container_image_preview': string;
  'product__container_info': string;
  'product__container_info_characteristics': string;
  'product__container_info_characteristics_first_column': string;
  'product__container_info_characteristics_second_column': string;
  'product__container_product': string;
  'product__container_product_actions': string;
  'product__container_product_addToBasket': string;
  'product__container_product_addToBasketCounter': string;
  'product__container_product_addToFavorite': string;
  'product__container_product_available': string;
  'product__container_product_baseinfo': string;
  'product__container_product_buyNow': string;
  'product__container_product_price': string;
  'product__container_product_title': string;
  'product__main': string;
  'product_container_info_description': string;
  'toastBody': string;
  'toastContainer': string;
  'toastProgress': string;
}
export const cssExports: CssExports;
export default cssExports;
