// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'smallitem_container': string;
  'smallitem_image': string;
  'smallitem_info_amountCounter': string;
  'smallitem_main': string;
}
export const cssExports: CssExports;
export default cssExports;
