// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content__wrap': string;
  'page__container': string;
  'toastContainer': string;
  'toastBody': string;
  'toastProgress': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
