// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'user__content': string;
  'user__content_avatar_image': string;
  'user__content_background_image': string;
  'user__content_background_image_buttons': string;
  'user__content_name': string;
}
export const cssExports: CssExports;
export default cssExports;
