// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main__userinfo': string;
  'main__userinfo_content': string;
  'main__userinfo_content_firsthalf': string;
  'main__userinfo_content_savebtn': string;
  'main__userinfo_content_secondhalf': string;
  'toastBody': string;
  'toastContainer': string;
  'toastProgress': string;
}
export const cssExports: CssExports;
export default cssExports;
