// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gradient': string;
  'welcome__container': string;
  'welcome__container_content': string;
  'welcome__container_openMarket': string;
  'welcome__container_title': string;
  'welcome__main': string;
}
export const cssExports: CssExports;
export default cssExports;
